[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
build_unflags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -std=gnu++11
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MODE=0
    -std=gnu++17
lib_deps =
    https://github.com/pschatzmann/arduino-audio-tools
